-- ------------------------- info -------------------------
-- @@ver: 1_000_000
-- @@info: 初始化fa-demo模块
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS demo_student (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    age INTEGER,
    sex SMALLINT,
    email VARCHAR(255),
    birthday DATE,
    valid BOOLEAN DEFAULT TRUE,
    tags JSONB,
    info JSONB,
    info_id INTEGER,
    corp_id INTEGER NOT NULL,
    tenant_id INTEGER NOT NULL,
    crt_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    crt_user VARCHAR(32) NOT NULL,
    crt_name VARCHAR(255) NOT NULL,
    crt_host VARCHAR(255),
    upd_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    upd_user VARCHAR(32),
    upd_name VARCHAR(255),
    upd_host VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
);
COMMENT ON TABLE demo_student IS 'DEMO-学生表';
COMMENT ON COLUMN demo_student.id IS 'ID';
COMMENT ON COLUMN demo_student.name IS '学生名';
COMMENT ON COLUMN demo_student.age IS '年龄';
COMMENT ON COLUMN demo_student.sex IS '性别';
COMMENT ON COLUMN demo_student.email IS '邮箱';
COMMENT ON COLUMN demo_student.birthday IS '生日';
COMMENT ON COLUMN demo_student.valid IS '账户是否有效';
COMMENT ON COLUMN demo_student.tags IS '标签数组';
COMMENT ON COLUMN demo_student.info IS '详细信息';
COMMENT ON COLUMN demo_student.info_id IS '补充信息ID';
COMMENT ON COLUMN demo_student.corp_id IS '企业ID';
COMMENT ON COLUMN demo_student.tenant_id IS '租户ID';
COMMENT ON COLUMN demo_student.crt_time IS '创建时间';
COMMENT ON COLUMN demo_student.crt_user IS '创建用户ID';
COMMENT ON COLUMN demo_student.crt_name IS '创建用户';
COMMENT ON COLUMN demo_student.crt_host IS '创建IP';
COMMENT ON COLUMN demo_student.upd_time IS '更新时间';
COMMENT ON COLUMN demo_student.upd_user IS '更新用户ID';
COMMENT ON COLUMN demo_student.upd_name IS '更新用户';
COMMENT ON COLUMN demo_student.upd_host IS '更新IP';
COMMENT ON COLUMN demo_student.deleted IS '是否删除';

CREATE TABLE IF NOT EXISTS demo_student_info (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    info1 VARCHAR(255),
    info2 VARCHAR(255),
    crt_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    crt_user VARCHAR(32) NOT NULL,
    crt_name VARCHAR(255) NOT NULL,
    crt_host VARCHAR(255),
    upd_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    upd_user VARCHAR(32),
    upd_name VARCHAR(255),
    upd_host VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
);
COMMENT ON TABLE demo_student_info IS 'DEMO-学生表-扩充信息表';
COMMENT ON COLUMN demo_student_info.id IS 'ID';
COMMENT ON COLUMN demo_student_info.info1 IS '补充信息1';
COMMENT ON COLUMN demo_student_info.info2 IS '补充信息2';

CREATE TABLE IF NOT EXISTS demo_tree (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    sort INTEGER DEFAULT 0,
    crt_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    crt_user VARCHAR(32) NOT NULL,
    crt_name VARCHAR(255) NOT NULL,
    crt_host VARCHAR(255),
    upd_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    upd_user VARCHAR(32),
    upd_name VARCHAR(255),
    upd_host VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
);
COMMENT ON TABLE demo_tree IS 'DEMO-Tree结构数据';
COMMENT ON COLUMN demo_tree.id IS 'ID';
COMMENT ON COLUMN demo_tree.parent_id IS '上级节点';
COMMENT ON COLUMN demo_tree.name IS '名称';
COMMENT ON COLUMN demo_tree.sort IS '排序ID';

DROP TRIGGER IF EXISTS demo_student__upd_time ON demo_student;
CREATE TRIGGER demo_student__upd_time
    BEFORE UPDATE ON demo_student
    FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

DROP TRIGGER IF EXISTS demo_student_info__upd_time ON demo_student_info;
CREATE TRIGGER demo_student_info__upd_time
    BEFORE UPDATE ON demo_student_info
    FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

DROP TRIGGER IF EXISTS demo_tree__upd_time ON demo_tree;
CREATE TRIGGER demo_tree__upd_time
    BEFORE UPDATE ON demo_tree
    FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Records of base_rbac_menu
-- ----------------------------
BEGIN;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20000000, 0, '组件示例', 1, 0, 'icons', TRUE, 1, '/admin/demo', '2023-01-03 16:07:53', '1', '超级管理员1', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20010000, 20000000, '通用组件', 0, 1, 'fa-solid fa-cubes', TRUE, 1, '/admin/demo/biz', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20020000, 20000000, '表格查询', 1, 1, 'fa-solid fa-table', TRUE, 1, '/admin/demo/table', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20030000, 20000000, '进阶功能', 2, 0, 'fa-solid fa-rocket', TRUE, 1, '/admin/demo/advance', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20040000, 20000000, '图表展示', 3, 1, 'chart-line', TRUE, 1, '/admin/demo/chart', '2023-02-23 10:48:58', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;

INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20010100, 20010000, '图标', 0, 1, '', TRUE, 1, '/admin/demo/biz/icon', '2023-01-03 16:07:53', '1', '超级管理员1', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20010200, 20010000, '权限测试', 1, 1, NULL, TRUE, 1, '/admin/demo/biz/authTest', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20010201, 20010200, '权限按钮', 0, 9, NULL, TRUE, 1, '/admin/demo/biz/authTest@button1', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20010300, 20010000, '地址选择器', 2, 1, NULL, TRUE, 1, '/admin/demo/biz/areaCascader', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20010400, 20010000, '富文本编辑器', 3, 1, NULL, TRUE, 1, '/admin/demo/biz/tinymce', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20010500, 20010000, '文件上传', 4, 1, NULL, TRUE, 1, '/admin/demo/biz/fileUploader', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20010600, 20010000, '级联选择', 6, 1, NULL, TRUE, 1, '/admin/demo/biz/cascader', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20010700, 20010000, '字典选择器', 5, 1, NULL, TRUE, 1, '/admin/demo/biz/dict', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20010800, 20010000, '拖动排序', 9, 1, NULL, TRUE, 1, '/admin/demo/biz/drag', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20010900, 20010000, '远程数据选择', 8, 1, NULL, TRUE, 1, '/admin/demo/biz/select', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20011000, 20010000, '远程数据Tree', 7, 1, NULL, TRUE, 1, '/admin/demo/biz/tree', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20012000, 20010000, 'PDF预览', 11, 1, NULL, TRUE, 1, '/admin/demo/biz/pdfView', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20013000, 20010000, '路由选择', 10, 1, NULL, TRUE, 1, '/admin/demo/biz/route', '2023-01-04 14:53:10', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20014000, 20010000, 'tailwindcss', 12, 1, NULL, TRUE, 1, '/admin/demo/biz/tailwindcss', '2023-01-06 14:20:51', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20015000, 20010000, '日期选择', 13, 1, NULL, TRUE, 1, '/admin/demo/biz/datepicker', '2023-01-06 16:44:21', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20016000, 20010000, '页面标签', 14, 1, NULL, TRUE, 1, '/admin/demo/biz/openTabs', '2023-02-13 13:58:35', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20017000, 20010000, '右键菜单', 15, 1, NULL, TRUE, 1, '/admin/demo/biz/contextMenu', '2023-02-13 14:01:04', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;

INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20020100, 20020000, '表格查询', 0, 1, NULL, TRUE, 1, '/admin/demo/table/table', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20020200, 20020000, '组合查询', 1, 1, NULL, TRUE, 1, '/admin/demo/table/conditionQuery', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;

INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20030100, 20030000, 'socket连接', 0, 1, NULL, TRUE, 1, '/admin/demo/advance/socket', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20030200, 20030000, 'redis缓存', 1, 1, NULL, TRUE, 1, '/admin/demo/advance/redis', '2023-01-03 16:07:53', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;

INSERT INTO base_rbac_menu (id, parent_id, name, sort, level, icon, status, link_type, link_url, crt_time, crt_user, crt_name, crt_host, upd_time, upd_user, upd_name, upd_host, deleted) VALUES (20040100, 20040000, 'echarts', 0, 1, NULL, TRUE, 1, '/admin/demo/chart/echartsDemo', '2023-02-23 10:49:05', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE) ON CONFLICT (id) DO NOTHING;

COMMIT;

SELECT setval(
    pg_get_serial_sequence('base_rbac_menu', 'id'),
    COALESCE((SELECT MAX(id) FROM base_rbac_menu), 1),
    TRUE
);
